### PR TITLE
Display the address of the server 

### PR DESCRIPTION
**Pull request by ThinkRedstone**
solves #242 .
Colour of the address is subject to change; To me, it seems the easiest to see.

I don't know if there's a better way to display the server IP without adding a new middleware and adding a new file.

address is not a very good name for that file, should probably be changed, but I have no idea for a better name.

### CODE REVIEW

**Comment by alanggreen** [comment]
https://www.npmjs.com/package/ip is used a lot.
3,646,381 downloads in the last month

**Comment by idanstark42** [comment]
I think about it, and seems pointless to show the IP in the client side when you can already see it in the URL line in the browser. Roey added a link from the server desktop to each service (using the icons in the right side of the task bar), so I think it's pretty much answers the requirement we had there. I don't think we need this part of the code, what do you think?

**Comment by ThinkRedstone** [comment]
The idea behind this PR is to make it easier for the head ref to instruct the refs as to what address to write to get access to the server, because before anyone outside localhost connects, the main computer is the only one connected; and it only displays localhost in the address bar. If JJ's links open the correct page using the server's ip and not localhost, then this PR is pretty pointless, feel free to close it. Otherwise, the PR might have some use.

**Comment by idanstark42** [comment]
I say we leave it as is, without closing it, and without maintaining it any further, until we can see the link that JJ had made, and then we can make a decision.

**Comment by idanstark42** [comment]
I'm closing this PR beause it was decided not to go with this route

**Pull request closed without merging**
