### PR TITLE
Added logo to login background and a button to show the password

### PR DESCRIPTION
**Pull request by ThinkRedstone**
This is as far as I can take it. @idanstark42 if you can make it scale to the proper size on mobile and find somewhere to stick the message it should be done

### CODE REVIEW

**Comment by alanggreen** [comment]
Idan, Dafner

Please merge this to a dev branch and not to master. Not sure what
signature pad address is, but these are "nice to have" and not required
when there is a code freeze
Let me know if you feel differently, and I'll explain.

Thanks
Alan

**Comment by ThinkRedstone** [comment]
@alanggreen The "code freeze" idea is not enforced here. If we merge into master here, it doesn't affect practically anything. Where the idea of final version comes into play is the Launcher- each module in the launcher has a version associated with it, and without pushing a new version to npm and updating the required version in the launcher, it won't change the code the launcher actually runs.

**Comment by alanggreen** [comment]
@ThinkRedstone The launcher is part of the code just like the display or
the scoring, and one can introduce unintended bugs there too. In the life
of any software project there is a point where one has to say "Stop, no
more changes. We need stability now". We're at that point now. If there is
no code freeze then you can't know whether tests that have been completed
successfully are valid anymore.

**Comment by ThinkRedstone** [comment]
@alanggreen Yes, but this PR is not in the launcher repo, it doesn't affect the launcher in any way

**Pull request merged**
